services:
  mysql:
    image: mysql:8.0
    container_name: brightbuy-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brightbuy
      MYSQL_USER: brightbuy
      MYSQL_PASSWORD: brightbuy
    ports:
      - "3307:3306"
    volumes:
      - brightbuy-data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --log-bin-trust-function-creators=1


volumes:
  brightbuy-data:
