-- =========================================================================
-- 002 — Catalogue                                          OWNER: M2
--
-- TODO(M2). Create, following the conventions of 001:
--   category            category_id PK, category_name, is_active,
--                       parent_category_id NULL self-FK               (REQ-10.2)
--   product             product_id PK, product_name, description,
--                       image_url, brand, is_active
--   product_category    PRIMARY KEY (product_id, category_id)          <- composite
--   variant             variant_id PK, product_id FK, SKU, price,
--                       stock_quantity, is_active
--                       UNIQUE (SKU)                                   (REQ-10.3)
--                       CHECK (price > 0)
--                       CHECK (stock_quantity >= 0)                    (REQ-6.3)
--   variant_attribute   attribute_id PK, name          e.g. 'Colour'
--   attribute_value     value_id PK, attribute_id FK, variant_id FK, value
--                       UNIQUE (variant_id, attribute_id)
--
-- Note: MySQL 8.0.16+ enforces CHECK constraints. Confirm your version with
--   SELECT VERSION();   -- anything below 8.0.16 parses but ignores CHECK.
-- =========================================================================
