-- =========================================================================
-- 009 — Triggers                                           OWNER: M4
--
-- TODO(M4):
--   trg_variant_stock_no_negative  BEFORE UPDATE ON variant
--     IF NEW.stock_quantity < 0 THEN
--       SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Stock cannot be negative';
--     END IF;                                                     (REQ-6.3)
--
--   trg_stock_adjustment_audit  AFTER INSERT ON stock_adjustment
--     (optional) apply change_qty to variant.stock_quantity so the audit row
--     and the quantity can never disagree.                        (REQ-10.4)
--
-- Belt and braces: keep the CHECK constraint in 002 as well. The trigger gives
-- a clear error message; the CHECK is the guarantee.
-- =========================================================================
